#import "../template/template.typ": *

= Introduction

Linux operating system has been widely adopted in various domains from personal computers to servers and embedded systems@Wang2013ASO. The Linux kernel is the core component of the Linux operating system. It is essential for providing different kinds of crucial services like process management, file system and so on. Linux kernel is written mostly in C, which is a powerful but unsafe programming language because of its lack of memory safety features. These days, a memory safety issue in kernels can finally result in a security vulnerability which can be attacked by malicious users and result in a severe consequence@10sp.  In 2022, an engineer discovered the Dirty Pipe vulnerability (CVE-2022-0847)@kellermann2022dirtypipe. This vulnerability can help an attacker get root privileges on a system if the attacker has read access to a file. Rust is a modern programming language that provides memory safety guarantees without sacrificing performance. It has become more and more popular in the systems programming community. Researchers begin to use Rust to write kernel modules and even entire kernels like KeepOS, Asterinas, Kerla and so on@aster. 

However, many existing Linux kernel modules like device drivers and file systems are written in C. They can not directly work with Rust-based kernels. Based on this, ideas of using Rust to write Linux kernel modules have been proposed@rust_kernel_module. Also, there are a large number of C modules such as device drivers and it is hard to port all of them to Rust kernels. However, ensuring ABI(Application Binary Interface) Compatibility between Rust-based kernels and existing Linux kernel modules is crucial for the successful adoption of Rust in kernel development. ABI Compatibility means that the binary interface between the kernel and user-space applications or kernel modules remains consistent, allowing them to interact seamlessly without requiring modifications@binarylevel. Ensuring ABI Compatibility is essential for maintaining the stability and functionality of existing software while enabling the benefits of Rust's memory safety features in kernel development. 

Although kernel developers have made efforts to ensure ABI Compatibility when building Rust-based kernels, there are still challenges and potential issues that can arise. For most rust-based kernels, developers just write in the documentation that the kernel they develop is ABI compatible with the Linux kernel, but they do not provide a systematic way to verify the ABI Compatibility@258917. Existing tools like Syzkaller@syzkaller target finding bugs in the Linux kernel, but these tools cannot be directly used in the Rust-based kernels because of the differences in the kernel implementation and the lack of support for Rust-based kernels. Other widely used testing frameworks share the same limitation. Trinity@jones2010trinity, a system call fuzzer, generates semi-random arguments to stress-test syscall entry points, but it is tightly coupled to Linux-specific syscall tables and assumes a Linux kernel build environment, making it unsuitable for Rust-based kernels out of the box. Similarly, the Linux Test Project (LTP)@ltp provides thousands of conformance and regression tests for the Linux kernel, yet its test cases are written against Linux-specific behaviors and build infrastructure, and likewise cannot be applied to Rust-based kernels without substantial adaptation. What's more, these tools target finding bugs in the kernel, but finding bugs is not the same as finding ABI Compatibility issues. ABI Compatibility issues can be more subtle and may not be regarded as bugs in the kernel. In this case, there is a need for a systematic way to verify the ABI Compatibility of Rust-based kernels with existing Linux kernel modules.

Recently, large language models (LLMs) have shown great potential in various domains, including software development, code generation, and testing@chen2021evaluatinglargelanguagemodels@lu2021codexgluemachinelearningbenchmark. Many LLM-based test generation methods have been proposed, demonstrating strong capabilities in generating high-quality inputs and exploring complex program behaviors. However, directly applying these techniques to kernel-level ABI compatibility testing remains challenging due to the complexity of kernel interfaces and the lack of well-defined specifications@kernel_vul. Hallucination is also a common issue in LLM-based generation, where the model may produce programs that seem correct but are actually invalid or irrelevant to the target domain. This can lead to a large number of invalid test cases which may cause unnecessary computation overhead and reduce the effectiveness of testing. 

In particular, the Linux ABI is highly complex, involving numerous system calls, complicated data structures, and subtle interactions between user space and kernel space. Exhaustively verifying ABI compatibility across all possible interfaces is therefore infeasible in practice. To address this challenge, we propose to focus on a critical and well-defined subset of the ABI: system calls.

System calls are the only legitimate boundary through which user-space programs can interact with the kernel. All other observable kernel behaviors --- including file I/O, process management, inter-process communication, memory mapping, and device access --- are ultimately funneled through this interface. Higher-level constructs such as the C standard library, language runtimes, and even container or virtualization layers eventually bottom out in system calls. As a result, if a Rust-based kernel faithfully reproduces the syscall ABI of Linux, the vast majority of unmodified user-space binaries should run correctly on top of it. Conversely, any divergence at this layer will surface as visible misbehavior in real workloads. This makes system calls not only a well-scoped and tractable target, but also the single most informative layer at which to probe ABI compatibility.

However, system calls cannot be treated as independent, stateless functions. They are deeply stateful, and most meaningful syscalls only make sense within a sequence that establishes the required kernel state. A typical file-access workflow, for instance, follows the chain *open-write-read-close*: the file descriptor returned by `open` is a prerequisite for `write` and `read`, and `close` is only meaningful given a previously opened descriptor. A naive testing strategy that generates syscalls and arguments uniformly at random will have uncertain probability, invoke operations on invalid descriptors, unmapped addresses, or non-existent objects. Such tests provide little signal about ABI compatibility, because they never reach the parts of the kernel where divergence between Linux and a Rust-based reimplementation is most likely to manifest. An effective ABI compatibility tester must therefore be aware of these dependency chains and generate syscall sequences that respect resource lifetimes, rather than treating each call in isolation.

Based on this insight, we design and implement ABIscope, a seed generation tool tailored for ABI compatibility testing of Rust-based kernels. ABIscope leverages LLMs to generate system call sequences (seeds) and incorporates an intermediate parameter propagation mechanism, where arguments from previous system calls are reused and transformed for subsequent calls. This design enables ABIscope to construct semantically meaningful and stateful test cases, rather than isolated and random inputs.

Furthermore, ABIscope improves system call argument coverage by systematically exploring diverse parameter combinations and dependencies. By increasing the diversity and validity of system call inputs, ABIscope indirectly enhances kernel code coverage, as measured by KCOV. This approach allows us to effectively exercise deeper execution paths in the kernel without requiring intrusive instrumentation or kernel-specific adaptations.

We evaluate ABIscope on the file system, I/O, and memory management subsystems of multiple Rust-based kernels, including Asterinas and KeepOS and compare their behaviors against the Linux kernel. Our results reveal several previously undocumented ABI incompatibility issues, demonstrating that even kernels claiming ABI compatibility may exhibit inconsistencies in system call semantics and behaviors. These findings highlight the necessity of systematic ABI verification and showcase the effectiveness of ABIscope in uncovering such issues.

