#import "../template/template.typ": *

= Introduction

Linux operating system has been widely adopted in various domains from personal computers to servers and embedded systems(references). The Linux kernel is the core component of the Linux operating system. It is essential for providing different kinds of crucial services like process management,file system and so on. Linux kernel is written mostly in C, which is a powerful but unsafe programming language because of its lack of memory safety features(references). These days, a memory safety issue in kernels can finally result in a security vulnerability which be attacked by the malicious users and result in a severe consequence(references). Rust is a modern programming language that provides memory safety guarantees without sacrificing performance. It has become more and more popular in the systems programming community. Researchers begin to use Rust to write kernel modules and even entire kernels like KeepOS, Asterinas, Kerla and so on(references). 

However, many existing Linux kernel modules like device drivers and file systems are written in C. They can not directly work with Rust-based kernels. Based on this, ideas of using Rust to write Linux kernel modules is proposed.(references). However, ensuring ABI(Application Binary Interface) Compatibility between Rust-based kernels and existing Linux kernel modules is crucial for the successful adoption of Rust in kernel development. ABI Compatibility means that the binary interface between the kernel and user-space applications or kernel modules remains consistent, allowing them to interact seamlessly without requiring modifications. Ensuring ABI Compatibility is essential for maintaining the stability and functionality of existing software while enabling the benefits of Rust's memory safety features in kernel development. 

Although kernel developers have made efforts to ensure ABI Compatibility when building Rust-based kernels, there are still challenges and potential issues thay can arise. For most rust-based kernels, developers just write in the documentation that the kernel they develop is ABI compatible with the Linux kernel, but they do not provide a systematic way to verify the ABI Compatibility. Existing tools like Syzkaller target at finding bugs in the Linux kernel, but these tools cannot directly use in the Rust-based kernels because of the differences in the kernel implementation and the lack of support for Rust-based kernels. What's more, these tools target at finding bugs in the kernel, but finding bugs is not the same as finding ABI Compatibility issues. ABI Compatibility issues can be more subtle and may not be regarded as bugs in the kernel. In this case, there is a need for a systematic way to verify the ABI Compatibility of Rust-based kernels with existing Linux kernel modules.

Recently, large language models (LLMs) have shown great potential in various domains, including software development, code generation, and testing. Many LLM-based test generation methods have been proposed, demonstrating strong capabilities in generating high-quality inputs and exploring complex program behaviors. However, directly applying these techniques to kernel-level ABI compatibility testing remains challenging due to the complexity of kernel interfaces and the lack of well-defined specifications.

In particular, the Linux ABI is highly complex, involving numerous system calls, complicated data structures, and subtle interactions between user space and kernel space. Exhaustively verifying ABI compatibility across all possible interfaces is therefore infeasible in practice. To address this challenge, we propose to focus on a critical and well-defined subset of the ABI: system calls. System calls serve as the primary interface between user applications and the kernel, and thus provide an effective abstraction for testing ABI compatibility.

Based on this insight, we design and implement Abiscope, a seed generation tool tailored for ABI compatibility testing of Rust-based kernels. Abiscope leverages LLMs to generate system call sequences (seeds) and incorporates an intermediate parameter propagation mechanism, where arguments from previous system calls are reused and transformed for subsequent calls. This design enables Abiscope to construct semantically meaningful and stateful test cases, rather than isolated and random inputs.

Furthermore, Abiscope improves system call argument coverage by systematically exploring diverse parameter combinations and dependencies. By increasing the diversity and validity of system call inputs, Abiscope indirectly enhances kernel code coverage, as measured by KCOV. This approach allows us to effectively exercise deeper execution paths in the kernel without requiring intrusive instrumentation or kernel-specific adaptations.

We evaluate Abiscope on the file system subsystem of multiple Rust-based kernels, including Asterinas and KeepOS and compare their behaviors against the Linux kernel. Our results reveal several previously undocumented ABI incompatibility issues, demonstrating that even kernels claiming ABI compatibility may exhibit inconsistencies in system call semantics and behaviors. These findings highlight the necessity of systematic ABI verification and showcase the effectiveness of Abiscope in uncovering such issues.