#import "../template/template.typ": *

= Methodology

== Overview <sec-overview>
We present ABIscope, a novel tool designed to generate user-space test cases for differential analysis of Linux ABI Compatibility in Rust-based kernels targeting syscalls. The overall pipeline follows an iterative seed generation and evaluation process, leveraging LLMs with feedback-driven exploration. At a high level, ABIscope consists of four key stages: (1) Seed initialization (#ref(<sec-seed-initialization>, supplement: [Section])), (2) LLM-based mutation (#ref(<sec-LLM-based-mutation>, supplement: [Section])), (3) execution and validation (#ref(<sec-Execution-and-Validation>, supplement: [Section])), and (4) coverage-guided selection (#ref(<sec-coverage-guided-selection>, supplement: [Section])). These four key components form a closed feedback loop. The overall pipeline is illustrated in #ref(<fig-pipeline>, supplement: [Figure]). We describe each stage in detail in the following sections.

#figure(
	image(
		width: 100%,
		"../images/pipeline.png"
	),
	supplement: [Figure],
	caption: [Overall pipeline of ABIscope.]
) <fig-pipeline>

== Seed Initialization <sec-seed-initialization>
Linux ABI Compatibility is complicated by the fact that the Linux kernel provides a large number of system calls and different structures, each of them have their own ABI. It is impractical to generate test cases for all of them. To simplify the problem, we focus on a subset of system calls that are commonly used and have well-defined ABIs. We select a set of system calls of file system, I/O and memory management which are commonly used in kernel development and important for kernel stability and performance. We will generate programs in these three categories of system calls as the initial seeds for the mutation process.
=== Syzkaller and Syzlang Format
Syzkaller is a popular fuzzing tool for finding bugs in the Linux kernel developed by Google. It generates random inputs for system calls and monitors the kernel's behavior to identify potential vulnerabilities. But we cannot directly use Syzkaller for ABI Compatibility testing because incompatibility issues may not necessarily cause crashes or other easily detectable symptoms@loupe. Although the target of Syzkaller is to find bugs in the target kernel, it can still generate valid programs that involve syscalls we are interested in. Syzkaller seeds are written in Syzlang, a strong domain specific language designed for syscall sequences with explicit argument types, virtual memory address, typed file handles and so on. Syzlang is able to represent the structural intent of a test like syscalls to call and its order. However, Syzlang itself is not directly compilable, so we need to convert the Syzlang seeds generated by Syzkaller into C programs.
=== LLM-based Syzlang-to-C Translation with Probe Injection and Self-Repair
Syzkaller itself provides a tool to convert Syzlang seeds into C programs, but the result C programs provided by the tool are not always valid and compilable. Even if a program can compile and execute, it cannot guarantee the sandbox environment of the ABI testing process thus not suitable for our purpose. Also, our target is to see the return values and error codes of the syscalls, but the raw programs do not provide the mechanism to collect these information. To address these issues, we design a LLM-based Syzlang-to-C translation process with probe injection. The probe macro injection is a static rewriting process that scans the C source code for syscall invocations and inserts two types of macros: `LOG_SYSCALL_RES(name,ret)` and `LOG_STAT(name,ret,st)`. The former is used to record syscall name, return value and errno, while the latter is used for stat-family calls to record file attributes such as size, mode and so on. These probes will be executed at runtime to collect the necessary information for the future analysis. If compilation or execution fails, the error messages are fed back to the LLM to fix the test cases(up to 3 times in default). Programs that still fail after all repair attempts will be discarded. The valid and runnable C programs generated in this stage will be used as the initial seeds for the mutation process.
== LLM-based mutation <sec-LLM-based-mutation>
ABIscope adopts a mutation-based approach to generate new test cases from the initial seeds. We leverage LLMs to perform mutations on the valid test cases generated in the previous stage. The LLM takes the valid test cases as input and generates new test cases by applying various mutation strategies.
- Structure mutation: LLM can insert new syscalls to the test cases which can trigger new code paths in the kernel. For example, LLM can insert `mmap` syscall before `read` syscall to trigger the code path of memory mapping in the kernel. Also, LLM can remove some syscalls from the test cases to reach the edge cases. For example, LLM can remove `open` syscall from the test case to trigger the code path of handling invalid file descriptors to see the ability of the error-handling code in the rust-based kernel.
- Order mutation: LLM can change the order of the syscalls in the test cases to trigger different code paths in the kernel. For example, LLM can change the order of `rmdir` and `rename` syscalls to trigger the code path of handling directory operations in the kernel.
- Fault injection: LLM can inject faults into the test cases to trigger specific error-handling code paths in the kernel. We can find incompatibility issues through the different errno values returned by the syscalls.
- Logic mutation: LLM can construct stateful misuse patterns like double free, use-after-free and so on. The idea is the same as the logic mutation in AFL++ to see the compatibility of error-handling.
- Parameter mutation: LLM perturbs syscall arguments at both value and structure levels to expose ABI-sensitive boundary behavior. Concretely, it rewrites scalar parameters (e.g., file descriptors, offsets, lengths, and flags) toward the cases that never appear in the seeds before. For instance, it may generate negative offsets, oversized lengths, or uncommon flag combinations. LLM can effectively explore the argument space by learning from the existing seeds.
== Execution and Validation <sec-Execution-and-Validation>
After generating new test cases through LLM-based mutation, ABIscope executes these test cases on Linux first. If the test case can be executed successfully on Linux, we will execute the same test case on Rust-based kernels. If the generated programs cannot be executed successfully on Linux, we will involve another LLM to fix the test cases. If the repair process fails after limited attempts, we will discard the test cases. The execution results of the test cases on both Linux and Rust-based kernels will be collected and compared to evaluate the compatibility of the test cases. We will compare the return values, output parameters, and error codes of the syscalls to identify any discrepancies that may indicate ABI incompatibility issues. If we find any discrepancies, we will further analyze the test cases to understand the root cause of the incompatibility and write reports to summarize the issues we found.
== Coverage-Guided Selection <sec-coverage-guided-selection>
To quantify the effectiveness of LLM-generated mutations, ABIscope adopts SAC (System-call Argument Coverage) as its primary feedback signal. In contrast to conventional control-flow coverage (e.g., line, basic-block, or branch coverage collected through kernel instrumentation), SAC evaluates whether a mutated seed explores previously unseen argument semantics and externally observable execution outcomes. This formulation is particularly suitable for ABI compatibility analysis, where behavioral divergence may arise even when no crash or obvious control-flow anomaly is observed.

In our implementation, SAC integrates both static and dynamic evidence. The static dimension is extracted directly from generated C programs and includes: (i) flag-level behaviors, where individual macros (such as `O_RDWR`, `O_CREAT`, and `SEEK_END`) and their co-occurrence relations are encoded; (ii) path-pattern abstractions, where path-like literals are mapped to semantic categories defined by preconfigured pattern rules; (iii) numeric and alignment-sensitive arguments, including boundary values (e.g., `-1`, `0`), page-aligned constants, and oversized unsigned probes; and (iv) permission-mask semantics, where mode-related expressions are matched against predefined privilege-related masks to detect bits such as SUID/SGID.
=== Formal Definition of SAC

Let $sigma = (c, ell)$ denote a seed, where $c$ is the C source program and $ell$ is the runtime probe log obtained after compilation and execution. The SAC feature extraction function $Phi$ maps each seed to a set of symbolic feature tokens:

$ Phi(sigma) = Phi^s (c) union Phi^d (c, ell) $ <eq-sac-feature>

where $Phi^s$ denotes the static feature extractor operating on the source text, and $Phi^d$ denotes the dynamic feature extractor operating on the runtime log.

The static features are decomposed into five disjoint categories:

$ Phi^s (c) = Phi^"flag" (c) union Phi^"path" (c) union Phi^"int" (c) union Phi^"mode" (c) union Phi^"bound" (c) $ <eq-static-decomp>

Specifically:
- $Phi^"flag" (c)$ captures individual flag tokens $f in cal(F)$ and their line-level co-occurrence combinations. Each $f$ contributes token `FLAG:`$f$; any pair $(f_1, f_2)$ co-occurring on the same source line contributes `PAIR:`$f_1|f_2$; the full co-occurring set contributes a `COMBO:` token.
- $Phi^"path" (c)$ maps path-like string literals to semantic category tags (e.g., `PATH_DOT`, `PATH_DEEP_NEST`) via a set of predefined regular-expression rules.
- $Phi^"int" (c)$ records numeric boundary tokens including $0$, $-1$, page-aligned constants ($4096, 8192$), $2^31-1$, the sentinel $-100$ (`AT_FDCWD`), and overflow-range probes ($>= "0xFFFFFFFF"$).
- $Phi^"mode" (c)$ detects permission-mask bit patterns (SUID $= 0"o"4000$, SGID $= 0"o"2000$, sticky bit $= 0"o"1000$, etc.) within mode-parameter argument positions only, avoiding false positives from unrelated numeric literals.
- $Phi^"bound" (c)$ generates call-site-bound tokens of the form $"STATIC:"s":"alpha$ for each syscall $s in cal(S)$ and each attribute $alpha$ derived from its argument list, binding argument semantics to the specific call site rather than accumulating them globally.

Dynamic features are extracted per syscall occurrence. For the $k$-th occurrence of syscall $n$ in log $ell$, denoted $n^((k))$, the extractor produces:

#[
  #set text(size: 0.78em)
  $ Phi^d (c, ell) = union.big_(n^((k)) in ell) { "DYN:SYSCALL:"n, "DYN:SYSCALL_OCC:"n"#"k } union O(n^((k))) union E(n^((k))) union S(n^((k))) $
  <eq-dyn-features>
]

where $O(n^((k)))$ records the success/failure outcome and the exact return value; $E(n^((k)))$ records the concrete errno value on failure; and $S(n^((k)))$ records filesystem side-effects---file-size regime, link-count transition, and effective permission-mode bits---observed via `stat`-family probes. For syscalls that produce no observable filesystem side-effects (e.g., memory-management or pure I/O operations), $S(n^((k))) = emptyset$.

Let $G_t$ denote the global coverage set accumulated from the first $t$ accepted seeds. For a candidate seed $sigma$, the *coverage gain* is defined as the cardinality of the set difference between the seed's feature set and the current global coverage:

$ "gain"(sigma, G_t) = lr(|Phi(sigma) without G_t|) $ <eq-gain>

A seed is admitted into the corpus if and only if it introduces at least one novel feature token:

$ sigma "is accepted" "if and only if" "gain"(sigma, G_t) > 0 $ <eq-accept>

Upon acceptance, the global coverage set is updated monotonically:

$ G_(t+1) = G_t union Phi(sigma) $ <eq-update>

Seeds that do not increase $G_t$ are discarded, ensuring that the corpus grows only when genuinely new argument-semantic or execution-outcome evidence is encountered. Consequently, SAC serves as a non-instrumentation, semantics-oriented guidance mechanism that continuously steers the LLM toward high-value edge cases for ABI incompatibility discovery.

At each mutation step, ABIscope selects uniformly at random among the five mutation strategies: Structure mutation, Order mutation, Fault injection, Logic mutation, and Parameter mutation. Each is assigned equal probability $p = 1\/5$. The overall pipeline repeats until the maximum number of iterations or the time budget is exhausted.



== Threats to Validity <sec-threats-to-validity>
Despite the feedback-driven design of ABIscope, several validity threats still remain.

First, there are construct-validity threats in the coverage signal. SAC is designed to capture argument semantics and observable side effects, but it is still a proxy metric rather than a direct measure of incompatibility severity. A seed may produce positive SAC gain without exposing a meaningful ABI defect, while some true incompatibilities may exhibit limited gain if their behavioral signatures overlap with already observed patterns. To reduce this risk, SAC is evaluated jointly with differential execution outcomes and error-code distributions, rather than used as a standalone criterion.

Second, there are internal-validity threats in mutation and execution. LLM-based mutation is inherently stochastic and can be sensitive to prompt context, which may affect reproducibility across runs. In addition, generated tests can contain invalid or weakly constrained arguments; such cases may amplify input noise and obscure real kernel-level divergence. We therefore retain only compilable/runnable candidates and interpret failures together with runtime traces, so that parameter invalidity can be separated from compatibility-relevant behavioral differences.

Third, differential execution itself introduces confounding factors. Linux and Rust-based kernels may differ in scheduling behavior, timing, default configuration, and tolerance to undefined or implementation-dependent behavior. Some output discrepancies can therefore reflect environmental or semantic ambiguity rather than strict ABI incompatibility. To mitigate this issue, ABIscope compares aligned test inputs under controlled conditions and emphasizes stable, repeatable divergences.

Finally, there are external-validity limitations. The current setup focuses on a selected subset of file system, I/O, and memory management syscalls and may not fully generalize to other subsystems (e.g., networking, IPC, device drivers) or production workloads. Consequently, conclusions should be interpreted as evidence for the three studied syscall domains, with broader generalization requiring expanded syscall coverage and larger-scale cross-kernel evaluation.
